# -*- coding: utf-8 -*-
"""Desafío Raices de Ecuaciones SIS-254.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WhM-Mk-as6bPzxtChMoQc9WE9XiMEu_D
"""

import math
import numpy as np # Se añade numpy para algunas funciones matemáticas más robustas

# --- FUNCIONES DE LOS PROBLEMAS ---
# Problema 1: f(x) = x^3 - e^(0.8x) - 20
def f1(x):
    return x**3 - math.exp(0.8 * x) - 20
def df1(x):
    return 3 * x**2 - 0.8 * math.exp(0.8 * x)

# Problema 2: f(x) = 3 sin(0.5x) - 0.5x + 2
def f2(x):
    return 3 * math.sin(0.5 * x) - 0.5 * x + 2
def df2(x):
    return 1.5 * math.cos(0.5 * x) - 0.5

# Problema 3: f(x) = x^3 - x^2 * e^(-0.5x) - 3x + 1
def f3(x):
    # Uso de np.exp por si se requiere mayor robustez
    return x**3 - (x**2 * np.exp(-0.5 * x)) - 3 * x + 1
def df3(x):
    return 3 * x**2 - 2 * x * np.exp(-0.5 * x) + 0.5 * x**2 * np.exp(-0.5 * x) - 3

# Problema 4: f(x) = cos^2(x) - 0.5x * e^(0.3x) + 5
def f4(x):
    return math.cos(x)**2 - 0.5 * x * math.exp(0.3 * x) + 5
def df4(x):
    return -math.sin(2 * x) - 0.5 * math.exp(0.3 * x) - 0.15 * x * math.exp(0.3 * x)

# --- IMPLEMENTACIÓN DE LOS MÉTODOS NUMÉRICOS ---

def biseccion(f, a, b, tol=1e-5, max_iter=100):
    try:
        if f(a) * f(b) >= 0:
            return "Error: Signos iguales / No converge en el intervalo"

        for i in range(max_iter):
            c = (a + b) / 2
            if f(c) == 0 or (b - a) / 2 < tol:
                return c

            if f(c) * f(a) < 0:
                b = c
            else:
                a = c
        return c
    except OverflowError:
        return "Error: Overflow"

def newton_raphson(f, df, x0, tol=1e-5, max_iter=100):
    x = x0
    try:
        for i in range(max_iter):
            fx = f(x)
            dfx = df(x)

            if abs(dfx) < 1e-10:
                return "Error: Derivada muy cercana a cero"

            x_new = x - fx / dfx

            if abs(x_new - x) < tol:
                return x_new

            x = x_new
        return x
    except OverflowError:
        return "Error: Overflow"
    except ValueError:
        return "Error: Valor inválido"

def secante(f, x_prev, x_curr, tol=1e-5, max_iter=100):
    try:
        for i in range(max_iter):
            fx_prev = f(x_prev)
            fx_curr = f(x_curr)

            if abs(fx_curr - fx_prev) < 1e-10:
                return "Error: Denominador muy cercano a cero"

            x_next = x_curr - fx_curr * (x_curr - x_prev) / (fx_curr - fx_prev)

            if abs(x_next - x_curr) < tol:
                return x_next

            x_prev = x_curr
            x_curr = x_next
        return x_curr
    except OverflowError:
        return "Error: Overflow"
    except ValueError:
        return "Error: Valor inválido"

# Helper function to format results, handling both numbers and error strings
def format_result(result):
    if isinstance(result, (int, float)):
        return f"{result:.5f}"
    else:
        return str(result)

# --- EJECUCIÓN CON VALORES INICIALES AJUSTADOS ---
print("--- RESULTADOS POR MÉTODO (TOL=1e-5) ---")
print("Nota: Los valores iniciales fueron ajustados para asegurar la convergencia a cada raíz específica.")

# Problema 1: Raíces 3.20045 y 7.48998
print("\n1. Problema 1:")
print(f"  Bisección (R1): {format_result(biseccion(f1, 3.0, 4.0))} | (R2): {format_result(biseccion(f1, 7.0, 7.5))}")
print(f"  Newton (R1):    {format_result(newton_raphson(f1, df1, 3.2))} | (R2): {format_result(newton_raphson(f1, df1, 7.5))}")
print(f"  Secante (R1):   {format_result(secante(f1, 3.0, 3.5))} | (R2): {format_result(secante(f1, 7.0, 7.5))}")

# Problema 2: Raíz 5.70351
print("\n2. Problema 2:")
print(f"  Bisección: {format_result(biseccion(f2, 5.0, 6.0))}")
print(f"  Newton:    {format_result(newton_raphson(f2, df2, 5.7))}")
print(f"  Secante:   {format_result(secante(f2, 5.0, 6.0))}")

# Problema 3: Raíces -0.29087, 0.35284, 1.30714
print("\n3. Problema 3:")
# AJUSTES CLAVE EN NEWTON/SECANTE para asegurar las 3 raíces
print(f"  Bisección (R1): {format_result(biseccion(f3, -0.5, 0.0))} | (R2): {format_result(biseccion(f3, 0.0, 0.5))} | (R3): {format_result(biseccion(f3, 1.0, 2.0))}")
print(f"  Newton (R1):    {format_result(newton_raphson(f3, df3, -0.5))} | (R2): {format_result(newton_raphson(f3, df3, 0.3))} | (R3): {format_result(newton_raphson(f3, df3, 1.0))}")
print(f"  Secante (R1):   {format_result(secante(f3, -0.5, -0.3))} | (R2): {format_result(secante(f3, 0.0, 0.5))} | (R3): {format_result(secante(f3, 1.0, 2.0))}")

# Problema 4: Raíz 3.71630
print("\n4. Problema 4:")
print(f"  Bisección: {format_result(biseccion(f4, 3.0, 4.0))}")
print(f"  Newton:    {format_result(newton_raphson(f4, df4, 3.5))}")
print(f"  Secante:   {format_result(secante(f4, 3.0, 4.0))}")